=== bartek-jag/XML/hurtownia.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified"
    xmlns:typy="http://typy" xmlns:grupy="http://grupy">
    <xsd:import namespace="http://typy" schemaLocation="typy.xsd">
        <xsd:annotation>
            <xsd:documentation>Importuje niestandardowe typy używane w dokumencie</xsd:documentation>
        </xsd:annotation>
    </xsd:import>
    <xsd:import namespace="http://grupy" schemaLocation="grupy.xsd"/>
    <xsd:element name="hurtownia">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="napoje"/>
                <xsd:element ref="dostawcy"/>
                <xsd:element ref="producenci"/>
                <xsd:element ref="rodzaje"/>
            </xsd:sequence>
        </xsd:complexType>

        <xsd:key name="napojID">
            <xsd:annotation>
                <xsd:documentation>ID napojów</xsd:documentation>
            </xsd:annotation>
            <xsd:selector xpath="napoje/napoj"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:key name="producentNazwa">
            <xsd:annotation>
                <xsd:documentation>Nazwy producentów</xsd:documentation>
            </xsd:annotation>
            <xsd:selector xpath="producenci/producent"/>
            <xsd:field xpath="."/>
        </xsd:key>
        <xsd:key name="dostawcaKlucz">
            <xsd:annotation>
                <xsd:documentation>ID dostawców</xsd:documentation>
            </xsd:annotation>
            <xsd:selector xpath="dostawcy/dostawca"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:key name="rodzajKlucz">
            <xsd:annotation>
                <xsd:documentation>Nazwy rodzajów napoju</xsd:documentation>
            </xsd:annotation>
            <xsd:selector xpath="rodzaje/rodzaj"/>
            <xsd:field xpath="."/>
        </xsd:key>
        <xsd:keyref name="refDostawca" refer="dostawcaKlucz">
            <xsd:selector xpath="napoje/napoj"/>
            <xsd:field xpath="dostawcaID"/>
        </xsd:keyref>
        <xsd:keyref name="refRodzaj" refer="rodzajKlucz">
            <xsd:selector xpath="napoje/napoj"/>
            <xsd:field xpath="@rodzaj"/>
        </xsd:keyref>
        <xsd:keyref name="refProducent" refer="producentNazwa">
            <xsd:selector xpath="napoje/napoj"/>
            <xsd:field xpath="producent"/>
        </xsd:keyref>
    </xsd:element>

    <xsd:element name="napoje">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="napoj"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="napoj" type="pelneDaneNapoju"/>
    <xsd:complexType name="daneNapoju">
        <xsd:sequence>
            <xsd:element name="nazwa" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="producent" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>Referencja do nazwy producenta</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="dostawcaID" type="xsd:integer">
                <xsd:annotation>
                    <xsd:documentation>Referencja do ID dostawcy</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="gaz" type="typy:rodzajeGazu"/>
			<xsd:element name="smak" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="ilosc" type="xsd:nonNegativeInteger"/>
            <xsd:element name="cena" type="xsd:decimal">
                <xsd:annotation>
                    <xsd:documentation>Cena za jedną sztukę</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="kodyKreskowe" type="typy:kody" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="opis" type="xsd:string" minOccurs="0" maxOccurs="1">
                <xsd:annotation>
                    <xsd:documentation>Informacja dotycząca sposobu przychowywania napoju np. w kartonach lub skrzynkach. Rodzaj opakowania i jego pojemność</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="nieaktualne" use="optional" type="xsd:boolean">
            <xsd:annotation>
                <xsd:documentation>Użyty w przypadku gdy towar jest nieaktualny/uszkodzony i nie jest przeznaczony do sprzedaży</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="id" use="required" type="xsd:integer"/>
        <xsd:attribute name="rodzaj" use="required" type="xsd:NCName">
            <xsd:annotation>
                <xsd:documentation>Referencja do nazwy rodzaju napoju</xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="pelneDaneNapoju">
        <xsd:complexContent>
            <xsd:extension base="daneNapoju">
                <xsd:sequence>
                    <xsd:element name="notatka" type="typy:notka" minOccurs="0">
                        <xsd:annotation>
                            <xsd:documentation>Informacja dodatkowa</xsd:documentation>
                        </xsd:annotation>
                    </xsd:element>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="dostawcy">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="dostawca" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:choice>
                            <xsd:group ref="grupy:daneOsoby"/>
                            <xsd:group ref="grupy:daneFirmy"/>
                        </xsd:choice>
                        <xsd:attribute name="id" use="required" type="xsd:integer"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="emaileDostawców">
            <xsd:selector xpath="dostawca"/>
            <xsd:field xpath="email"/>
        </xsd:unique>
    </xsd:element>

    <xsd:element name="producenci">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="producent" maxOccurs="unbounded" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="rodzaje">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="rodzaj" maxOccurs="unbounded">
                    <xsd:complexType mixed="true">
                        <xsd:simpleContent>
                            <xsd:extension base="xsd:NCName">
                                <xsd:attribute name="podatek">
                                    <xsd:simpleType>
                                        <xsd:union>
                                            <xsd:simpleType>
                                                <xsd:restriction base="typy:wartoscPodatku"/>
                                            </xsd:simpleType>

                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                  <xsd:enumeration value="brak danych"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:union>
                                    </xsd:simpleType>
                                </xsd:attribute>
                            </xsd:extension>
                        </xsd:simpleContent>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== bartek-jag/XML/hurtownia.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="hurtownia.xsl"?>

<!--Tylko tabela napojów-->
<!--<?xml-stylesheet type="text/xsl" href="napoje.xsl"?>-->

<!--Tylko tabela dostawców-->
<!--<?xml-stylesheet type="text/xsl" href="dostawcy.xsl"?>-->

<!--Tylko tabela producentów-->
<!--<?xml-stylesheet type="text/xsl" href="producenci.xsl"?>-->

<hurtownia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hurtownia.xsd">
	<napoje>
		<napoj id="1" rodzaj="Sok">
			<nazwa>Kubuś</nazwa>
			<producent>Maspex</producent>
			<dostawcaID>1</dostawcaID>
			<gaz>niegazowany</gaz>
			<smak>jabłkowy</smak>
			<ilosc>3500</ilosc>
			<cena>2.1500</cena>
			<opis>Nowe opakowanie</opis>
		</napoj>
		<napoj id="2" rodzaj="Sok" nieaktualne="true">
			<nazwa>Kubuś</nazwa>
			<producent>Maspex</producent>
			<dostawcaID>1</dostawcaID>
			<gaz>niegazowany</gaz>
			<smak>bananowy</smak>
			<ilosc>3500</ilosc>
			<cena>2.1500</cena>
		</napoj>
		<napoj id="3" rodzaj="Napój">
			<nazwa>Mirinda</nazwa>
			<producent>Pepsi</producent>
			<dostawcaID>2</dostawcaID>
			<gaz>gazowany</gaz>
			<smak>gruszkowy</smak>
			<ilosc>2000</ilosc>
			<cena>2.9000</cena>
			<kodyKreskowe>1234567890123 12345678</kodyKreskowe>
		</napoj>
		<napoj id="4" rodzaj="Sok">
			<nazwa>Fortuna</nazwa>
			<producent>Fortuna</producent>
			<dostawcaID>3</dostawcaID>
			<gaz>niegazowany</gaz>
			<smak>pomarańczowy</smak>
			<ilosc>1500</ilosc>
			<cena>3.1500</cena>
		</napoj>
		<napoj id="5" rodzaj="Sok">
			<nazwa>Fortuna</nazwa>
			<producent>Fortuna</producent>
			<dostawcaID>3</dostawcaID>
			<gaz>niegazowany</gaz>
			<smak>wieloowocowy</smak>
			<ilosc>1000</ilosc>
			<cena>3.2500</cena>
		</napoj>
		<napoj id="6" rodzaj="Sok">
			<nazwa>Fortuna</nazwa>
			<producent>Fortuna</producent>
			<dostawcaID>3</dostawcaID>
			<gaz>niegazowany</gaz>
			<smak>jabłko-marchew</smak>
			<ilosc>3000</ilosc>
			<cena>4.8000</cena>
		</napoj>
		<napoj id="7" rodzaj="Sok">
			<nazwa>Fortuna</nazwa>
			<producent>Fortuna</producent>
			<dostawcaID>3</dostawcaID>
			<gaz>niegazowany</gaz>
			<smak>truskawka-jabłko</smak>
			<ilosc>3000</ilosc>
			<cena>2.7000</cena>
		</napoj>
		<napoj id="8" rodzaj="Woda">
			<nazwa>Cisowianka</nazwa>
			<producent>Cisowianka</producent>
			<dostawcaID>3</dostawcaID>
			<gaz>niegazowany</gaz>
			<ilosc>4000</ilosc>
			<cena>1.7000</cena>
		</napoj>
		<napoj id="9" rodzaj="Woda">
			<nazwa>Cisowianka</nazwa>
			<producent>Cisowianka</producent>
			<dostawcaID>3</dostawcaID>
			<gaz>lekkogazowany</gaz>
			<ilosc>4000</ilosc>
			<cena>1.7000</cena>
		</napoj>
		<napoj id="10" rodzaj="Woda">
			<nazwa>Cisowianka</nazwa>
			<producent>Cisowianka</producent>
			<dostawcaID>3</dostawcaID>
			<gaz>gazowany</gaz>
			<ilosc>4000</ilosc>
			<cena>1.7000</cena>
		</napoj>
		<napoj id="11" rodzaj="Piwo">
			<nazwa>Tyskie</nazwa>
			<producent>Kompania Piwowarska</producent>
			<dostawcaID>4</dostawcaID>
			<gaz>gazowany</gaz>
			<ilosc>3000</ilosc>
			<cena>2.0000</cena>
		</napoj>
		<napoj id="12" rodzaj="Piwo">
			<nazwa>Lech</nazwa>
			<producent>Kompania Piwowarska</producent>
			<dostawcaID>4</dostawcaID>
			<gaz>gazowany</gaz>
			<ilosc>3200</ilosc>
			<cena>2.0000</cena>
		</napoj>
		<napoj id="13" rodzaj="Piwo">
			<nazwa>Tatra</nazwa>
			<producent>Grupa Żywiec</producent>
			<dostawcaID>4</dostawcaID>
			<gaz>gazowany</gaz>
			<ilosc>3200</ilosc>
			<cena>1.8000</cena>
		</napoj>
		<napoj id="14" rodzaj="Piwo">
			<nazwa>Tyskie</nazwa>
			<producent>Kompania Piwowarska</producent>
			<dostawcaID>4</dostawcaID>
			<gaz>gazowany</gaz>
			<ilosc>3000</ilosc>
			<cena>2.0000</cena>
		</napoj>
		<napoj id="15" rodzaj="Napój">
			<nazwa>Hoop Cola</nazwa>
			<producent>Hoop</producent>
			<dostawcaID>1</dostawcaID>
			<gaz>gazowany</gaz>
			<ilosc>2000</ilosc>
			<cena>3.0000</cena>
		</napoj>
		<napoj id="16" rodzaj="Piwo">
			<nazwa>Żywiec</nazwa>
			<producent>Grupa Żywiec</producent>
			<dostawcaID>4</dostawcaID>
			<gaz>gazowany</gaz>
			<ilosc>2000</ilosc>
			<cena>2.5000</cena>
		</napoj>
	</napoje>
	<dostawcy>
		<dostawca id="1">
			<imie>Bronisław</imie>
			<nazwisko>Komar</nazwisko>
			<email>bronek.komar@zywiec.pl</email>
			<numerTelefonu>634345342</numerTelefonu>
		</dostawca>
		<dostawca id="2">
			<imie>Paweł</imie>
			<nazwisko>Gaweł</nazwisko>
			<email>p.gawel@magazyny.pl</email>
			<numerTelefonu>876655342</numerTelefonu>
		</dostawca>
		<dostawca id="3">
			<imie>Kamil</imie>
			<nazwisko>Jeż</nazwisko>
			<email>jezyk.kamil@soki.pl</email>
			<numerTelefonu>634354335</numerTelefonu>
		</dostawca>
		<dostawca id="4">
			<imie>Jakub</imie>
			<nazwisko>Kirkiewicz</nazwisko>
			<email>jakub.kirki@hellmann.pl</email>
			<numerTelefonu>637567662</numerTelefonu>
		</dostawca>
		<dostawca id="5">
			<nazwa>SuperDostawy Sp. z.o.o</nazwa>
			<nip>1234567890</nip>
			<numerTelefonu>840285923</numerTelefonu>
		</dostawca>
	</dostawcy>
	<producenci>
		<producent>Fortuna</producent>
		<producent>Cisowianka</producent>
		<producent>Grupa Żywiec</producent>
		<producent>Kompania Piwowarska</producent>
		<producent>Hoop</producent>
		<producent>Maspex</producent>
		<producent>Pepsi</producent>
	</producenci>
	<rodzaje>
		<rodzaj podatek="0.05">Sok</rodzaj>
		<rodzaj>Napój</rodzaj>
		<rodzaj podatek="0.22">Napój_energetyczny</rodzaj>
		<rodzaj podatek="0.22">Piwo</rodzaj>
		<rodzaj podatek="0.22">Wódka</rodzaj>
		<rodzaj podatek="0.05">Nektar</rodzaj>
		<rodzaj podatek="0.22">Woda</rodzaj>
	</rodzaje>
</hurtownia>
