=== bartek-jag/XML/rodzaje.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT rodzaje (rodzaj)+>
<!ELEMENT rodzaj ANY>
<!ATTLIST rodzaj podatek CDATA "0.23">
<!ATTLIST rodzaj nazwa ID #REQUIRED>

=== bartek-jag/XML/rodzaje_stare.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--<!DOCTYPE rodzaje SYSTEM "rodzaje.dtd">-->
    <rodzaje>
        <rodzaj podatek="0.05"></rodzaj>
        <rodzaj>Napój</rodzaj>
        <rodzaj podatek="0.22">Napój_energetyczny</rodzaj>
        <rodzaj podatek="0.22">Piwo</rodzaj>
        <rodzaj podatek="0.22">Wódka</rodzaj>
        <rodzaj podatek="0.05">Nektar</rodzaj>
        <rodzaj podatek="0.22">Woda</rodzaj>
    </rodzaje>

=== bartek-jag/XML/rodzaje.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--<!DOCTYPE rodzaje SYSTEM "rodzaje.dtd">-->
    <rodzaje>
        <rodzaj podatek="0.05" nazwa="Sok"/>
        <rodzaj nazwa="Napój"/>
        <rodzaj podatek="0.23" nazwa="Napój_energetyczny"/>
        <rodzaj podatek="0.23" nazwa="Piwo"/>
        <rodzaj podatek="0.23" nazwa="Wódka"/>
        <rodzaj podatek="0.05" nazwa="Nektar"/>
        <rodzaj podatek="0.23" nazwa="Woda"/>
    </rodzaje>
